### ISSUE TITLE
Request: Transitioning from Node 16 to Node 20

### ISSUE THREAD

**Issue by DHeyko-Akonovia** [py-actions/py-dependency-install#234]
As per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/, github actions will need to transition to node 20. Currently, the code is set to 16:

```
runs:
  using: "node16"
  main: "dist/index.js"
```
Thank you!

**Comment by chrissimpkins** [comment]
Thanks for the ping on this!

https://github.com/py-actions/py-dependency-install/pull/237

**Comment by chrissimpkins** [comment]
Released in `py-actions/py-dependency-install@v4.1.0`. You should receive it automatically if you are on `py-actions/py-dependency-install@v4`.

Thanks again!
